import { Box, Heading, useColorModeValue } from '@chakra-ui/react';
import Head from 'next/head';
import React, { ReactElement } from 'react';
import Layout from '../components/layout/Layout';

interface Props {}

function blog({}: Props): ReactElement {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box
          width="100%"
          p="50px"
          borderRadius="15"
          boxShadow="sm"
          bg={useColorModeValue('white', '#171717')}
        >
          <Heading as="h1" fontWeight="normal" fontSize="25">
            به بلاگ خوش آمدید
          </Heading>
        </Box>
      </Layout>
    </>
  );
}

export default blog;
