import { Box, Heading, useColorModeValue } from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import Header from '../components/layout/Header/Header';
import styles from '../styles/Home.module.css';
import Router from 'next/router';
import Loading from '../components/layout/Loading';
import Layout from '../components/layout/Layout';
import { UserDto } from '@portfolio/shared-types';
import { userService } from '@portfolio/data-access';
import { useQuery } from 'react-query';
import { useSession } from 'next-auth/client';

export default function Home() {
  const [Users, setUsers] = useState<UserDto[]>([]);
  const [session] = useSession();
  const { data, status } = useQuery('users', () => userService.fetchUsers(), {
    enabled: !!session,
  });
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box
          width="100%"
          p="50px"
          borderRadius="15"
          boxShadow="sm"
          bg={useColorModeValue('white', '#171717')}
        >
          <Heading as="h1" fontWeight="normal" fontSize="25">
            به پنل مدیریت خوش آمدید
          </Heading>
          <div>
            <h3>lets see</h3>
            {status === 'loading' && <div>{status}</div>}
            {status === 'error' && <div>{status}</div>}
            {status === 'success' &&
              data.map((user) => {
                console.log('map');
                return <div key={user.email}>{user.email}</div>;
              })}
          </div>
        </Box>
      </Layout>
    </>
  );
}
