import { Box, Heading, useColorModeValue } from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import Header from '../components/layout/Header/Header';
import styles from '../styles/Home.module.css';
import Router from 'next/router';
import Loading from '../components/layout/Loading';
import { signOut, useSession } from 'next-auth/client';
import Layout from '../components/layout/Layout';
import { UserDto } from '@portfolio/shared-types';
import { userService } from '@portfolio/data-access';

export default function Home() {
  // const { signUp, loading, error, user } = useAuth();
  // useEffect(() => {
  //   if (!loading) {
  //     console.log('as', user);
  //     if (error) {
  //       console.log('er', error);
  //     }
  //     if (!user) {
  //       Router.push('/login');
  //     }
  //   }
  // }, [user, loading]);
  const [Users, setUsers] = useState<UserDto[]>([]);
  const [session] = useSession();
  useEffect(() => {
    if (session) {
      userService.fetchUsers().then((data) => {
        setUsers(data);
        console.log(data);
      });
    }
  }, [session]);
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box
          width="100%"
          p="50px"
          borderRadius="15"
          boxShadow="sm"
          bg={useColorModeValue('white', '#171717')}
        >
          <Heading as="h1" fontWeight="normal" fontSize="25">
            به پنل مدیریت خوش آمدید
          </Heading>
        </Box>
      </Layout>
    </>
  );
}
