import { Box, Heading, useColorModeValue } from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Header from '../components/layout/Header/Header';
import SidebarWithHeader from '../components/layout/Sidebar/SidebarWithHeader';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SidebarWithHeader>
        <Box
          width="100%"
          p="50px"
          borderRadius="15"
          boxShadow="sm"
          bg={useColorModeValue('white', '#171717')}
        >
          <Heading as="h1" fontWeight="normal" fontSize="25">
            به پنل مدیریت خوش آمدید
          </Heading>
        </Box>
      </SidebarWithHeader>
    </>
  );
}
